name: cash_in_group
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.2
  decimal: 3.0.2
  equatable: ^2.0.7
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_storage: ^12.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.3
  image_picker: ^1.1.2
  intl: any
  leancode_lint: ^6.0.0
  loading_animation_widget: ^1.3.0
  provider: ^6.1.2
  shared_preferences: ^2.4.0

dev_dependencies:
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
  uses-material-design: true
  generate: true
