name: cash_in_group
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  decimal: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.6.3
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
